name: deeplearning-handson
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - comm=0.2.2
  - contourpy=1.3.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - debugpy=1.8.13
  - decorator=5.2.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freetype=2.13.3
  - icu=73.1
  - importlib-metadata=8.6.1
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=9.0.2
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - joblib=1.4.2
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20250127.0
  - libcups=2.4.2
  - libcurl=8.12.1
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=14.2.0
  - libiconv=1.16
  - libmpdec=4.0.0
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libsodium=1.0.18
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.13.5
  - lz4-c=1.9.4
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mysql=8.4.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - numexpr=2.10.1
  - numpy=2.2.4
  - numpy-base=2.2.4
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.4.1
  - packaging=24.2
  - pandas=2.2.3
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.50
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - python=3.13.2
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - python_abi=3.13
  - pytz=2024.1
  - pyzmq=26.2.0
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - readline=8.2
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - setuptools=72.1.0
  - sip=6.10.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.13.1
  - tzdata=2025a
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xcb-util-cursor=0.1.4
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
