name: deeplearning-handson
channels:
  - defaults
dependencies:
  - appnope=0.1.3=py313hca03da5_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - blas=1.0=openblas
  - bottleneck=1.4.2=py313ha35b7ea_0
  - brotli-python=1.0.9=py313h313beb8_9
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.2.25=hca03da5_0
  - comm=0.2.1=py313hca03da5_0
  - contourpy=1.3.1=py313h48ca7d4_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.8.11=py313h313beb8_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - deprecated=1.2.13=py313hca03da5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.4=h313beb8_0
  - filelock=3.13.1=py313hca03da5_0
  - fonttools=4.55.3=py313h80987f9_0
  - freetype=2.12.1=h1192e45_0
  - fsspec=2024.12.0=py313hca03da5_0
  - gmp=6.3.0=h313beb8_0
  - gmpy2=2.2.1=py313h5c1b81f_0
  - importlib-metadata=8.5.0=py313hca03da5_0
  - ipykernel=6.29.5=py313hca03da5_1
  - ipython=8.30.0=py313hca03da5_0
  - jedi=0.19.2=py313hca03da5_0
  - jinja2=3.1.6=py313hca03da5_0
  - jpeg=9e=h80987f9_3
  - jupyter_client=8.6.3=py313hca03da5_0
  - jupyter_core=5.7.2=py313hca03da5_0
  - kiwisolver=1.4.8=py313h313beb8_0
  - lcms2=2.16=he93ba84_0
  - lerc=4.0.0=h313beb8_0
  - libabseil=20240116.2=cxx17_h313beb8_0
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.22=h80987f9_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libmpdec=4.0.0=h80987f9_0
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libprotobuf=4.25.3=h514c7bf_0
  - libsodium=1.0.18=h1a28f6b_0
  - libtiff=4.5.1=hc9ead59_1
  - libtorch=2.5.1=gpu_mps_h82d5d13_202
  - libuv=1.48.0=h80987f9_0
  - libwebp-base=1.3.2=h80987f9_1
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=3.0.2=py313h80987f9_0
  - matplotlib=3.10.0=py313hca03da5_1
  - matplotlib-base=3.10.0=py313hb68df00_0
  - matplotlib-inline=0.1.6=py313hca03da5_0
  - mpc=1.3.1=h80987f9_0
  - mpfr=4.2.1=h80987f9_0
  - mpmath=1.3.0=py313hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=py313hca03da5_0
  - networkx=3.4.2=py313hca03da5_0
  - nomkl=3.0=0
  - numexpr=2.10.1=py313h5d9532f_0
  - numpy=2.2.4=py313h7c57ca2_0
  - numpy-base=2.2.4=py313hb98e858_0
  - openjpeg=2.5.2=h54b8e55_0
  - openssl=3.0.16=h02f6b3c_0
  - opentelemetry-api=1.30.0=py313hca03da5_0
  - packaging=24.2=py313hca03da5_0
  - pandas=2.2.3=py313hcf29cfe_0
  - parso=0.8.4=py313hca03da5_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=11.1.0=py313h84e58ab_0
  - pip=25.0=py313hca03da5_0
  - platformdirs=3.10.0=py313hca03da5_0
  - prompt-toolkit=3.0.43=py313hca03da5_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py313h80987f9_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.15.1=py313hca03da5_1
  - pyparsing=3.2.0=py313hca03da5_0
  - python=3.13.2=h4862095_100_cp313
  - python-dateutil=2.9.0post0=py313hca03da5_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.13=0_cp313
  - pytorch=2.5.1=gpu_mps_py313h80af30b_202
  - pytz=2024.1=py313hca03da5_0
  - pyzmq=26.2.0=py313h313beb8_0
  - readline=8.2=h1a28f6b_0
  - setuptools=72.1.0=py313hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sleef=3.5.1=h80987f9_2
  - sqlite=3.45.3=h80987f9_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.13.3=py313hca03da5_1
  - tk=8.6.14=h6ba3021_0
  - tornado=6.4.2=py313h80987f9_0
  - traitlets=5.14.3=py313hca03da5_0
  - typing_extensions=4.12.2=py313hca03da5_0
  - tzdata=2025a=h04d1e81_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.45.1=py313hca03da5_0
  - wrapt=1.17.0=py313h80987f9_0
  - xz=5.6.4=h80987f9_1
  - zeromq=4.3.5=h313beb8_0
  - zipp=3.21.0=py313hca03da5_0
  - zlib=1.2.13=h18a0788_1
  - zstd=1.5.6=hfb09047_0
prefix: /opt/anaconda3/envs/deeplearning-handson
